config/routes.rb
Rails.application.routes.draw do
  
  resources :songs

  resources :shows

  resources :contacts, only: [:new, :create]
  
  get 'contacts/new'
  
  root  'static_pages#home'
  match '/biography',    to: 'static_pages#biography',    via: 'get'
  match '/discography',   to: 'static_pages#discography',   via: 'get'
  match '/songs', to: 'static_pages#songs', via: 'get'
  match '/shows',   to: 'static_pages#shows',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  

end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/show.rb
class Show < ActiveRecord::Base
end

app/models/song.rb
class Song < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

     def new
          @contact = Contact.new
     end

     def create
          @contact = Contact.new(contact_params)
          if @contact.save
               ContactMailer.sent(@contact).deliver  # sentアクションにcontactの情報をもたせます。
               flash[:success] = "Thanks!! We'll be in touch."
               redirect_to root_url
          end
     end

     private

          def contact_params
               params.require(:contact).permit(:name, :email, :content)
          end

end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  before_action :set_show, only: [:show, :edit, :update, :destroy]

  # GET /shows
  # GET /shows.json
  def index
    @shows = Show.all
  end

  # GET /shows/1
  # GET /shows/1.json
  def show
  end

  # GET /shows/new
  def new
    @show = Show.new
  end

  # GET /shows/1/edit
  def edit
  end

  # POST /shows
  # POST /shows.json
  def create
    @show = Show.new(show_params)

    respond_to do |format|
      if @show.save
        format.html { redirect_to @show, notice: 'Show was successfully created.' }
        format.json { render :show, status: :created, location: @show }
      else
        format.html { render :new }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shows/1
  # PATCH/PUT /shows/1.json
  def update
    respond_to do |format|
      if @show.update(show_params)
        format.html { redirect_to @show, notice: 'Show was successfully updated.' }
        format.json { render :show, status: :ok, location: @show }
      else
        format.html { render :edit }
        format.json { render json: @show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shows/1
  # DELETE /shows/1.json
  def destroy
    @show.destroy
    respond_to do |format|
      format.html { redirect_to shows_url, notice: 'Show was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_show
      @show = Show.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def show_params
      params.require(:show).permit(:title, :official_title, :offical_url, :img_url, :sponser, :sponser_url, :broadcasting_station, :broadcasting_period, :youtube_id)
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:title, :music, :music_url, :lyrics, :singer, :illustration, :pv_director, :youtube_id, :itunes_url)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def biography
  end

  def discography
  end

  def songs
  end

  def shows
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # ページごとの完全なタイトルを返します。
  def full_title(page_title)
    base_title = "Mio Himemiya Official Page"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/shows_helper.rb
module ShowsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/contacts/confirm.html.erb
    <h1>お問い合わせ内容確認</h1>

    <%= form_for @contact, :url => contact_thanks_path do |f| %>
      <table>
        <tr>
          <th>名前</th>
          <td>
            <%= f.hidden_field :name %>
            <%= @contact.name %>
          </td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td>
            <%= f.hidden_field :email %>
            <%= @contact.email %>
          </td>
        </tr>
        <tr>
          <th>お問い合わせ内容</th>
          <td>
            <%= f.hidden_field :content %>
            <%= simple_format(@contact.message) %>
          </td>
        </tr>
      </table>
      <%= f.submit '送信', :class => 'btn btn-primary' %>
    <% end %>

app/views/contacts/new.html.slim
- provide(:title, 'Contact Form')
.container-fluid
  .container_bg.img-rounded.col-xs-10.col-xs-offset-1
    .row
      .col-xs-6.col-xs-offset-3
        h1
          | Contact
        = form_for(@contact) do |f|
          = render 'shared/error_messages', object: f.object
          p
            = f.label :name
            |      
            = f.text_field :name
            br
          p
            = f.label :email
            |      
            = f.text_field :email
            br
          p
            = f.label :content
            |   
            = f.text_area :content, class: "form-control", rows:3
          .center
           |  All the field is required. 
           br
           br
           = f.submit "Submit", class: "btn btn-large btn-primary"

app/views/contacts/thanks.html.erb
    <h1>お問い合わせ完了</h1>
    <p>以下の様に承りました。</p>
    <table>
      <tr>
        <th>名前</th>
        <td>
          <%= @contact.name %>
        </td>
      </tr>
      <tr>
        <th>メールアドレス</th>
        <td>
          <%= @contact.email %>
        </td>
      </tr>
      <tr>
        <th>お問い合わせ内容</th>
        <td>
          <%= simple_format(@contact.message) %>
        </td>
      </tr>
    </table>

app/views/layouts/_header.html.slim
header.navbar.navbar-fixed-bottom.navbar-inverse
  |  　
  .navbar-inner
    = link_to "Mio Himemiya Official Page", '/', id: "logo"
    |  　 　
    #menu-box
      #toggle
          | menu
      ul#menu.nav.pull-right
        li
          = link_to "Biography", biography_path
        li
          = link_to "Discography", discography_path
        li
          = link_to "Songs", songs_path
        li
          = link_to "Shows", shows_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = full_title(yield(:title))
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    script[src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"]
    script[src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"]
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    = render 'layouts/shiv'
  body
    span.bg
      = render 'layouts/header'
    = yield

app/views/shared/_error_messages.html.slim
- if @contact.errors.any?
  .alert.alert-danger[role="alert"]
    strong
      | There're any errors!
    ul
      - @contact.errors.each do |attr, msg|
        li
          = msg

app/views/shows/_form.html.slim
= form_for(@show) do |f|
  - if @show.errors.any?
    #error_explanation
      h2
        = pluralize(@show.errors.count, "error")
        |  prohibited this show from being saved:
      ul
        - @show.errors.full_messages.each do |message|
          li
            = message
  .field
    = f.label :title
    br
    = f.text_field :title
  .field
    = f.label :official_title
    br
    = f.text_area :official_title
  .field
    = f.label :offical_url
    br
    = f.text_field :offical_url
  .field
    = f.label :img_url
    br
    = f.text_field :img_url
  .field
    = f.label :sponser
    br
    = f.text_field :sponser
  .field
    = f.label :sponser_url
    br
    = f.text_field :sponser_url
  .field
    = f.label :broadcasting_station
    br
    = f.text_field :broadcasting_station
  .field
    = f.label :broadcasting_period
    br
    = f.text_field :broadcasting_period
  .field
    = f.label :youtube_id
    br
    = f.text_field :youtube_id
  .actions
    = f.submit

app/views/shows/_result.html.erb
<div class="container-fluid">
  <div class="row">
    <p>
      <h1>
        <%= @show.title %>
      </h1>
    </p>
  <div class="col-sm-4">
    <!--img class="img-result" src="%= image_tag @show.img_url if @show.img_url %"-->
    <%= image_tag @show.img_url if @show.img_url %>
  </div>
  <div class="col-sm-7 col-sm-offset-1">
    <p>
      <strong>Official title:</strong>
      <%= @show.official_title %>
    </p>
    <p>
      <% if @show.offical_url? %>
      <strong>Offical webpage:  </strong>
      <%= link_to @show.offical_url, @show.offical_url , :target=>["_blank"]%>
      <% end %>
    </p>
    <p>
      <% if @show.sponser_url? %>
      <strong>Sponser:  </strong>
      <%= link_to @show.sponser, @show.sponser_url, :target=>["_blank"]%>
      <% end %>
    </p>
    <p>
      <% if @show.broadcasting_station? %>
      <strong>Broadcasting station:</strong>
      <%= @show.broadcasting_station %>
      <% end %>
    </p>
    <p>
      <% if @show.broadcasting_period? %>
      <strong>Broadcasting period:</strong>
      <%= @show.broadcasting_period %>
      <% end %>
    </p>
  </div>
    <p>
    <% if @show.youtube_id? %>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/<%= @show.youtube_id %>" frameborder="0" allowfullscreen></iframe>
    <% end %>
    </p>
  </div>
</div>

app/views/shows/_sidebar.html.slim
.btn-group
  button.btn.btn-info.dropdown-toggle[type="button" data-toggle="dropdown"]
    |  Choose a show 
    span.caret
  ul.dropdown-menu[role="menu" aria-labelledby="dropdownMenu"]
    li.dropdown-header
      |  Radio Shows
    li
      a[tabindex="-1" href="/shows/1"]
        | Mana*Mio In Radio!
    li
      a[tabindex="-1" href="/shows/2"]
        | The Future Times(R) of Kawasaki Family
    li.divider
    li.dropdown-header
      |  Web Shows
    li
      a[tabindex="-1" href="/shows/3"]
        | Mirai Au Lait
    li
      a[tabindex="-1" href="/shows/4"]
        | Enjoy Mooma Tonight, too!
    li.divider
    li.dropdown-header
      |  Other Shows and Gigs
    li
      a[href="/shows/5"]
        | Gal-loween
    li
      a[href="/shows/6"]
        | Kawasaki City Events and Web Shows

app/views/shows/edit.html.slim
h1
  | Editing show
= render 'form'
= link_to 'Show', @show
|  | 
= link_to 'Back', shows_path

app/views/shows/index.html.slim
- provide(:title, 'Shows')
.container-fluid
  .col-sm-10.col-sm-offset-1
    .row
      .col-sm-2
        = render 'shows/sidebar'
      .container_bg.img-rounded.col-sm-9
        h2
          |  Choose a show title from sidebar. 

app/views/shows/new.html.slim
h1
  | New show
= render 'form'
= link_to 'Back', shows_path

app/views/shows/show.html.slim
- provide(:title, 'Shows')
.col-sm-10.col-sm-offset-1
  .row
    .col-sm-2
      = render 'shows/sidebar'
    .container_bg.img-rounded.col-sm-9
      = render 'shows/result'

app/views/songs/_form.html.slim
= form_for(@song) do |f|
  - if @song.errors.any?
    #error_explanation
      h2
        = pluralize(@song.errors.count, "error")
        |  prohibited this song from being saved:
      ul
        - @song.errors.full_messages.each do |message|
          li
            = message
  .field
    = f.label :title
    br
    = f.text_field :title
  .field
    = f.label :music
    br
    = f.text_field :music
  .field
    = f.label :music_url
    br
    = f.text_field :music_url
  .field
    = f.label :lyrics
    br
    = f.text_field :lyrics
  .field
    = f.label :singer
    br
    = f.text_field :singer
  .field
    = f.label :illustration
    br
    = f.text_field :illustration
  .field
    = f.label :pv_director
    br
    = f.text_field :pv_director
  .field
    = f.label :youtube_id
    br
    = f.text_field :youtube_id
  .field
    = f.label :itunes_url
    br
    = f.text_field :itunes_url
  .actions
    = f.submit

app/views/songs/_result.html.erb
<div class="container-fluid">
  <p>
    <h1>
      <%= @song.title %>
    </h1>
  </p>
  <div class="row">
    <div class="col-sm-7">
      <div class="video-wrap">
        <p>
          <% if @song.youtube_id? %>
          <iframe src="https://www.youtube.com/embed/<%= @song.youtube_id %>" frameborder="0" allowfullscreen></iframe>
          <% end %>
        </p>
      </div>
    </div>
    <div class="col-sm-4">
      <p>
        <strong>Music:</strong>
        <%= link_to @song.music, @song.music_url, :target=>["_blank"] %>
      </p>
      <p>
        <strong>Lyrics:</strong>
        <%= @song.lyrics %>
      </p>
      <p>
        <strong>Singer:</strong>
        <%= @song.singer %>
      </p>
      <p>
        <% if @song.illustration? %>
        <strong>Illustration:</strong>
        <%= @song.illustration %>
        <% end %>
      </p>

      <p>
        <% if @song.pv_director? %>
        <strong>Director:</strong>
        <%= @song.pv_director %>
        <% end %>
      </p>

      <p>
        <% if @song.itunes_url? %>
        <strong>This song is sold on <%= link_to 'itunes', @song.itunes_url , :target=>["_blank"] %></strong>
        <% end %>
      </p>
    </div>
  </div>
</div>

app/views/songs/_sidebar.html.slim
.btn-group
  button.btn.btn-primary.dropdown-toggle[type="button" data-toggle="dropdown"]
    |  Choose a song 
    span.caret
  ul.dropdown-menu[role="menu" aria-labelledby="dropdownMenu"]
    li.dropdown-header
      |  mooma
    li
      a[tabindex="-1" href="/songs/1"]
        | Ikenaiwa
    li
      a[tabindex="-1" href="/songs/2"]
        | Amazing Tokio
    li
      a[tabindex="-1" href="/songs/3"]
        | A Freshwater Fish
    li
      a[tabindex="-1" href="/songs/4"]
        | Mirai Planetarium
    li
      a[tabindex="-1" href="/songs/5"]
        | Kutsuwa
    li
      a[tabindex="-1" href="/songs/6"]
        | A, Un
    li
      a[tabindex="-1" href="/songs/7"]
        | True Good Bye
    li.divider
    li.dropdown-header
      |  ManaMio
    li
      a[tabindex="-1" href="/songs/8"]
        | Jitaku Kakuchou Keikaku
    li.divider
    li.dropdown-header
      |  Collaboration
    li
      a[tabindex="-1" href="/songs/9"]
        | Nekomance
    li
      a[tabindex="-1" href="/songs/10"]
        | 3, 2, 1, FIGHT!

app/views/songs/edit.html.slim
h1
  | Editing song
= render 'form'
= link_to 'Show', @song
|  | 
= link_to 'Back', songs_path

app/views/songs/index.html.slim
- provide(:title, 'Songs')
.container-fluid
  .col-sm-10.col-sm-offset-1
    .row
      .col-sm-2
        = render 'songs/sidebar'
      .container_bg.img-rounded.col-sm-9
        h2
          |  Choose a song title from sidebar. 

app/views/songs/new.html.slim
h1
  | New song
= render 'form'
= link_to 'Back', songs_path

app/views/songs/show.html.slim
- provide(:title, 'Songs')
.container-fluid
  .col-sm-10.col-sm-offset-1
    .row
      .col-sm-2
        = render 'songs/sidebar'
      .container_bg.img-rounded.col-sm-9
        = render 'songs/result'

app/views/static_pages/biography.html.slim
- provide(:title, 'Biography')
.container-fluid
  .container_bg.img-rounded.col-xs-10.col-xs-offset-1
    h1
      | Biography
    .row
      .col-xs-12.col-sm-6.col-md-4
        img.img-responsive[src="/assets/red.jpg" alt="mio"]
      .col-xs-12.col-sm-6.col-md-8
        h2
          | Mio Himemiya
        p
          | Born into an artistic family, Mio was exposed to music, art, and animation at a young age. After graduating from Keio University, she started performing. Not only doing music, Mio had talent in design, MCing, and modeling. She reached the 1st Rank in web voting on Myspace Japan's "Pretty Collection" contest. 
          br
          |  Mio performed and recorded in a Dark Electro duo called HimemaniK from 2007 to 2010. They released 
          i
            | Wanna Be a Figurine
          |  in 2009 and traveled to perform in Mexico in 2010.
          br
          br
          |  In 2011, Mio began working as a voice actress and started her solo music career as Mooma. Working with composer, Yasufumi Watanabe, Mio wrote all the lyrics and Mooma‘s first album, 
          i
            |  Ikenaiwa 
          |  was released in 2011. Mooma traveled to Los Angeles to perform in 2011.
          br
          |  In 2012, Mio was busy producing and MCing. She produced and co-MC’ed an FM radio show entitled 
          i
            | Mana*Mio In Radio! 
          | . In addition to that, she produced, wrote, and acted on another FM radio show called 
          i
            | The Future Times(R) of Kawasaki Family 
          | . Mio also produced and MC’ed a Web TV show called 
          i
            | Mirai Au Lait 
          | . 
          br
          br
          |  These days, Mio is focusing more on singing jazz. She traveled to New York in the summer of 2014 and studied Jazz singing and performed at many jazz clubs. She performed with the Niza Jazz Ensemble upon her return to Japan at the Yokohama Jazz Promenade in October of 2014. 
    .row
      h2
        | Articles
      a[href="http://diversejapan.com/2011/09/06/interview-mio-himemiyamooma-j-pop-singersongwriter-voice-actress-race-queen/" target="_blank"]
        | Diverse Japan (English)
      br
      a[href="http://japanvibes.fr/?p=1754" target="_blank"]
        | Japan Vibes(French)

app/views/static_pages/contact.html.slim
- provide(:title, 'Contact')

app/views/static_pages/discography.html.slim
- provide(:title, 'Discography')
.container-fluid
  .container_bg.img-rounded.col-xs-10.col-xs-offset-1
    h1
      | Discography
    .row
      .col-xs-12.col-sm-6.col-md-7
        img.img-responsive[src="/assets/MiraiP1000.jpg" alt="Album Mirai Planetarium"]
      .col-xs-12.col-sm-6.col-md-5
        h1
          | Album 
          br
          | "Mirai Planetarium"
        p
          | Realeased on Dec 24th 2014
          br
          br
          |  artist: mooma
          br
          |  Available on 
          a[href="https://itunes.apple.com/us/album/mirai-planetarium/id952275739" target="_blank"]
            | itunes
          |  or 
          a[href="http://www.amazon.com/Mirai-Planetarium-EP-mooma/dp/B00R5GJO9K" target="_blank"]
            | amazon

app/views/static_pages/home.html.slim
- provide(:title, '')
.container
  .row
    .col-sm-12
      h1#home_font
        | Album 
        br
        | "Mirai Planetarium"
        br
        |  now on sale
  .row
    .col-sm-12.homeyoutube
      .embed-responsive.embed-responsive-16by9
        iframe[width="960" height="506" src="https://www.youtube.com/embed/DmIrCKv-wJ4?list=PL68579E69B191D52B&amp;showinfo=0" frameborder="0" allowfullscreen]

app/views/static_pages/shows.html.slim
- provide(:title, 'Shows')

app/views/static_pages/songs.html.slim
- provide(:title, 'Songs')
.container-fluid
  .sidebar.container_bg
    .btn-group
      button.btn.btn-primary.dropdown-toggle[type="button" data-toggle="dropdown"]
        |  Choose a show 
        span.caret
      ul.dropdown-menu[role="menu"]
        li.dropdown-header
          | mooma
        li
          a[href="#"]
            | Ikenaiwa
        li
          a[href="#"]
            | Amazing Tokio
        li
          a[href="#"]
            | A Freshwater Fish
        li
          a[href="#"]
            | Mirai Planetarium
        li
          a[href="#"]
            | Kutsuwa
        li
          a[href="#"]
            | A, Un
        li
          a[href="#"]
            | True Good Bye
        li.divider
        li.dropdown-header
          | manamio
        li
          a[href="#"]
            | Jitaku Kakucho Keikaku
        li.divider
        li.dropdown-header
          | Collabration
        li
          a[href="#"]
            | Nekomance / Ultra Flesh
        li
          a[href="#"]
            | 3,2,1 -FIGHT! / Ultra Flesh
    script[src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"]
    script[src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"]
    p
      strong
        |  You can buy all the songs of mooma at 
        a[href="https://itunes.apple.com/us/album/mirai-planetarium/id952275739" target="_blank"]
          | itunes music
        | . 
  .content.container_bg
    .container_inside_right
      h2
        |  Choose the title from sidebar. 